### ISSUE TITLE
python3 stats.py : wont run (syntax error)

### ISSUE THREAD

**Issue by Geongsi** [mklements/OLED_Stats#19]
I got to the very last step and received an error code, I will list below, I even tried it on a new OS with a new micro SD and same error code (this is for Retropie).

pi@pi:~/OLED_Stats $ python3 stats.py
Traceback (most recent call last):
  File "stats.py", line 11, in <module>
    import adafruit_ssd1306
  File "/usr/local/lib/python3.7/dist-packages/adafruit_ssd1306.py", line 17, in <module>
    from adafruit_bus_device import i2c_device, spi_device
  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_bus_device/i2c_device.py", line 15, in <module>
    from circuitpython_typing import ReadableBuffer, WriteableBuffer
  File "/home/pi/.local/lib/python3.7/site-packages/circuitpython_typing/__init__.py", line 79
    def read(self, count: Optional[int] = None, /) -> Optional[bytes]:
                                                ^
SyntaxError: invalid syntax

Thanks in advance!

**Comment by mklements** [comment]
Retropie doesn't have the same libraries and dependencies installed as Raspberry Pi OS, so some packages may need to be added/updated to get it to run.
